pull_request_rules:
  - name: Automatic merge - dependabot
    description: Automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - check-success = cargo-checkmate
      - check-success = semver-check
      - check-success = udeps-check
      - check-success = codecov-check
      - check-success = clippy
    actions:
      merge:
        method: squash
